### ISSUE TITLE
problem, don't work with heroku

### ISSUE THREAD

**Issue by paolo2989** [akramsystems/chatfuel_dialogflow#1]
Hi, i'm using this code and clone it to heroku but it don't send data to dialog , what could be wrong

**Comment by akramsystems** [comment]
Make sure to Specify within your heroku app a value for **API_AI_KEY** , set it equal to the client access token of your dialogflow agent

In Chatfuel within your bot go to **Default Answer Block** and add a **User Input** block (link [here](https://docs.chatfuel.com/plugins/plugin-documentation/user-input)), leave _Message to User_ empty and specify the _Save Answer to Attribute_ to be **{{queryString}}** 

under your **Default Answer Block** add a **JSON API** object as a **GET** request (link [here])(https://docs.chatfuel.com/api/json-api/json-api)  and paste your heroku app's url where it says _URL_,  lastly put in **{{queryString}}** under _User Attributes_

This should solve your problem the only thing is it is only triggered when Chatfuel, I modified an existing version of this.  You can find the original version [here](https://www.notion.so/Tutorials-1eaeb0673e144d58a38e9a67e3253b5c) . Their version just involves a lot more redirecting blocks and stuff while mine just goes to the default answer and sends and receives messages without having to make Blocks or anything from Dialogflows side really.

**Comment by paolo2989** [comment]
Hi i’m sorry but this not work, i set up API_AI_KEY and all thing in chatfuel, the bot works but when it trigger dialogflow the bot not respond. This could be a problem of heroku free version ? 

Inviato da Posta per Windows 10

Da: Ali Akram
Inviato: mercoledì 13 giugno 2018 22:16
A: akramsystems/chatfuel_dialogflow
Cc: paolo2989; Author
Oggetto: Re: [akramsystems/chatfuel_dialogflow] problem, don't work withheroku (#1)

Make sure to Specify within your heroku app a value for API_AI_KEY , set it equal to the client access token of your dialogflow agent
In Chatfuel within your bot go to Default Answer Block and add a User Input block (link here), leave Message to User empty and specify the Save Answer to Attribute to be {{queryString}}
under your Default Answer Block add a JSON API object as a GET request (link [here])(https://docs.chatfuel.com/api/json-api/json-api) and paste your heroku app's url where it says URL, lastly put in {{queryString}} under User Attributes
This should solve your problem the only thing is it is only triggered when Chatfuel, I modified an existing version of this. You can find the original version here . Their version just involves a lot more redirecting blocks and stuff while mine just goes to the default answer and sends and receives messages without having to make Blocks or anything from Dialogflows side really.

**Comment by paolo2989** [comment]
This is the error. 
: Starting process with command `node index.js`
2018-06-15T16:29:52.404870+00:00 app[web.1]: running on port 46431
2018-06-15T16:29:53.993503+00:00 heroku[web.1]: State changed from starting to up
2018-06-15T16:36:02.047107+00:00 heroku[router]: at=info method=GET path= "/?queryString=How+are+you" host=arcane-basin-42821.herokuapp.com request_id=dd934fdb-20ee-4716-805d-7ff65d7bf886 fwd="13.68.77.206" dyno=web.1 connect=1ms service=5ms status=500 bytes=404 protocol=https
2018-06-15T16:36:02.031814+00:00 app[web.1]: TypeError: Cannot read property 'toString' of undefined
2018-06-15T16:36:02.032226+00:00 app[web.1]: at /app/index.js:23:45
2018-06-15T16:36:02.032230+00:00 app[web.1]: at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5)
2018-06-15T16:36:02.032233+00:00 app[web.1]: at next (/app/node_modules/express/lib/router/route.js:137:13)
2018-06-15T16:36:02.032235+00:00 app[web.1]: at Route.dispatch (/app/node_modules/express/lib/router/route.js:112:3)
2018-06-15T16:36:02.032236+00:00 app[web.1]: at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5)
2018-06-15T16:36:02.032239+00:00 app[web.1]: at /app/node_modules/express/lib/router/index.js:281:22
2018-06-15T16:36:02.032241+00:00 app[web.1]: at Function.process_params (/app/node_modules/express/lib/router/index.js:335:12)
2018-06-15T16:36:02.032242+00:00 app[web.1]: at next (/app/node_modules/express/lib/router/index.js:275:10)
2018-06-15T16:36:02.032244+00:00 app[web.1]: at jsonParser (/app/node_modules/body-parser/lib/types/json.js:110:7)
2018-06-15T16:36:02.032246+00:00 app[web.1]: at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5)
2018-06-15T16:36:02.045127+00:00 app[web.1]: TypeError: Cannot read property 'toString' of undefined
2018-06-15T16:36:02.045131+00:00 app[web.1]: at /app/index.js:23:45
2018-06-15T16:36:02.045133+00:00 app[web.1]: at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5)
2018-06-15T16:36:02.045135+00:00 app[web.1]: at next (/app/node_modules/express/lib/router/route.js:137:13)
2018-06-15T16:36:02.045137+00:00 app[web.1]: at Route.dispatch (/app/node_modules/express/lib/router/route.js:112:3)
2018-06-15T16:36:02.045139+00:00 app[web.1]: at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5)
2018-06-15T16:36:02.045140+00:00 app[web.1]: at /app/node_modules/express/lib/router/index.js:281:22
2018-06-15T16:36:02.045142+00:00 app[web.1]: at Function.process_params (/app/node_modules/express/lib/router/index.js:335:12)
2018-06-15T16:36:02.045144+00:00 app[web.1]: at next (/app/node_modules/express/lib/router/index.js:275:10)
2018-06-15T16:36:02.045145+00:00 app[web.1]: at jsonParser (/app/node_modules/body-parser/lib/types/json.js:110:7)
2018-06-15T16:36:02.045147+00:00 app[web.1]: at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5)

Inviato da Posta per Windows 10

Da: Ali Akram
Inviato: mercoledì 13 giugno 2018 22:16
A: akramsystems/chatfuel_dialogflow
Cc: paolo2989; Author
Oggetto: Re: [akramsystems/chatfuel_dialogflow] problem, don't work withheroku (#1)

Make sure to Specify within your heroku app a value for API_AI_KEY , set it equal to the client access token of your dialogflow agent
In Chatfuel within your bot go to Default Answer Block and add a User Input block (link here), leave Message to User empty and specify the Save Answer to Attribute to be {{queryString}}
under your Default Answer Block add a JSON API object as a GET request (link [here])(https://docs.chatfuel.com/api/json-api/json-api) and paste your heroku app's url where it says URL, lastly put in {{queryString}} under User Attributes
This should solve your problem the only thing is it is only triggered when Chatfuel, I modified an existing version of this. You can find the original version here . Their version just involves a lot more redirecting blocks and stuff while mine just goes to the default answer and sends and receives messages without having to make Blocks or anything from Dialogflows side really.

**Comment by akramsystems** [comment]
Can you take screen shots of the chatfuel Default answer block? And Also
you used the client access token  from dialog flow as the API_AI_KEY in
Heroku?

Screenshots will help me understand more about your problem :)

**Comment by paolo2989** [comment]
Here are screen shots of both chatfuel and logs of heroku app.
Thank you 


Inviato da Posta per Windows 10

Da: Ali Akram
Inviato: sabato 16 giugno 2018 20:21
A: akramsystems/chatfuel_dialogflow
Cc: paolo2989; Author
Oggetto: Re: [akramsystems/chatfuel_dialogflow] problem, don't work withheroku (#1)

Can you take screen shots of the chatfuel Default answer block? And Also
you used the client access token from dialog flow as the API_AI_KEY in
Heroku?

Screenshots will help me understand more about your problem :)

**Comment by akramsystems** [comment]
In Chatfuel under your JSON API under User Atributes add {{ messenger user id }} it should be a predefined field already.
![screen shot 2018-06-20 at 6 34 05 pm](https://user-images.githubusercontent.com/12886526/41688167-007d5b96-74b9-11e8-913f-a1594a2d2dfc.png)
